<div id="agenda">

    <h2 class="h2Calendar">Agenda de la semaine</h2>
    <h3>
        <?= htmlspecialchars($out[70]) ?>
    </h3>

    <table id="tableAgenda">

        <thead>

            <tr>
                <th></th>
                <th>Lundi</th>
                <th>Mardi</th>
                <th>Mercredi</th>
                <th>Jeudi</th>
                <th>Vendredi</th>
                <th>Samedi</th>
                <th>Dimanche</th>
            </tr>

        </thead>

        <tbody>
            <tr>
                <th>9h</th>
                <?php for ($n = 0; $n <= 6; $n++) : ?>
                <td>
                    <?= htmlspecialchars($out[$n]) ?>
                </td>
                <?php endfor; ?>
            </tr>
            <tr>
                <th>10h</th>
                <?php for ($n = 7; $n <= 13; $n++) : ?>
                <td>
                    <?= htmlspecialchars($out[$n]) ?>
                </td>
                <?php endfor; ?>
            </tr>
            <tr>
                <th>11h</th>
                <?php for ($n = 14; $n <= 20; $n++) : ?>
                <td>
                    <?= htmlspecialchars($out[$n]) ?>
                </td>
                <?php endfor; ?>
            </tr>
            <tr>
                <th>12h</th>
                <?php for ($n = 21; $n <= 27; $n++) : ?>
                <td>
                    <?= htmlspecialchars($out[$n]) ?>
                </td>
                <?php endfor; ?>
            </tr>
            <tr>
                <th>13h</th>
                <?php for ($n = 28; $n <= 34; $n++) : ?>
                <td>
                    <?= htmlspecialchars($out[$n]) ?>
                </td>
                <?php endfor; ?>
            </tr>
            <tr>
                <th>14h</th>
                <?php for ($n = 35; $n <= 41; $n++) : ?>
                <td>
                    <?= htmlspecialchars($out[$n]) ?>
                </td>
                <?php endfor; ?>
            </tr>
            <tr>
                <th>15h</th>
                <?php for ($n = 42; $n <= 48; $n++) : ?>
                <td>
                    <?= htmlspecialchars($out[$n]) ?>
                </td>
                <?php endfor; ?>
            </tr>
            <tr>
                <th>16h</th>
                <?php for ($n = 49; $n <= 55; $n++) : ?>
                <td>
                    <?= htmlspecialchars($out[$n]) ?>
                </td>
                <?php endfor; ?>
            </tr>
            <tr>
                <th>17h</th>
                <?php for ($n = 56; $n <= 62; $n++) : ?>
                <td>
                    <?= htmlspecialchars($out[$n]) ?>
                </td>
                <?php endfor; ?>
            </tr>
            <tr>
                <th>18h</th>
                <?php for ($n = 63; $n <= 69; $n++) : ?>
                <td>
                    <?= htmlspecialchars($out[$n]) ?>
                </td>
                <?php endfor; ?>
            </tr>
        </tbody>

    </table>


    <!-- <div id="stockTaches">
        <h1>Liste de tâches</h1>
        <input id="item" placeholder="Tâche">

        <table>
            <thead>
                <tr>
                    <th>Tâches</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="liste">
                <tr>
                    <td>Pomme</td>
                    <td><button class="btn btn-danger" onClick="effacer(this)">Effacer</button></td>
                </tr>
            </tbody>
        </table>
    </div> -->
</div>