<h2>Contactez-nous</h2>
            
<section class="contact">
            
    <article class="mailto">
        
        <h3><i class="fas fa-paper-plane"></i> Par mail</h3>
        
        <p>Me contacter par <a href="mailto: maxime.titsaoui@hotmail.fr">mail</a></p>
        
        <p>maxime.titsaoui@hotmail.fr</p>
        
    </article>
    
    <article class="social">
        
        <h3><i class="fas fa-user-friends"></i> Nos réseaux sociaux</h3>
        
        <a href="https://www.youtube.com/user/faim3r"><i class="fab fa-youtube"></i></a>
        
        <a href="https://www.twitch.tv/salamazine"><i class="fab fa-twitch"></i></a>
        
        <a href="https://twitter.com/PilouVideo"><i class="fab fa-twitter"></i></a>
        
        <a href="https://www.facebook.com/PilouVideo"><i class="fab fa-facebook-f"></i></a>
        
    </article>
            
</section>